// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomControls","status":true,"description":"v1.0 Example plugin template showing parameters and commands (MZ)","parameters":{}}
];
